filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/suricata/eve.json # il file che filebeat deve monitorare
    json.keys_under_root: true # per avere i campi json come campi di primo livello
    json.add_error_key: true # per avere info su eventuali errori
    fields:
      type: suricata
    fields_under_root: true # come "json.keys_under_root" ma per i campi "fields" (custom)

output.elasticsearch:
  hosts: ['elasticsearch:9200'] # dove inviare i log raccolti
  index: 'suricata-%{+yyyy.MM.dd}' # indice in elasticsearch

setup.kibana:
  host: 'kibana:5601'

# Configurazione del template Elasticsearch
setup.template.name: 'suricata'
setup.template.pattern: 'suricata-*'
setup.template.enabled: true
setup.template.overwrite: true # permette di sovrascrivere template esistenti in caso avessero stesso nome

setup.ilm.enabled: false # disabilita Index Lifecycle Management
logging.level: info

# Aggiunge metadati ai documenti
processors:
  - add_host_metadata: ~ # info sull'host
  - add_cloud_metadata: ~ # info sul cloud provider (se presente)
  - add_docker_metadata: ~ #info sui container docker
