%YAML 1.1
---
# Configurazione di base di Suricata

vars:
  address-groups:
    HOME_NET: '[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]'
    EXTERNAL_NET: '!$HOME_NET'

default-rule-path: /etc/suricata/rules
rule-files:
  - custom.rules

outputs:
  - fast:
      enabled: yes
      filename: fast.log
      append: yes

  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      types:
        - alert
        - http
        - dns
        - tls
        - files
        - ssh
        - flow

af-packet:
  - interface: eth0
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes

app-layer:
  protocols:
    http:
      enabled: yes
    tls:
      enabled: yes
