# ./suricata/config/suricata.yaml
%YAML 1.1
---
vars:
  address-groups:
    HOME_NET: '[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]'
    EXTERNAL_NET: '!$HOME_NET'

default-rule-path: /etc/suricata/rules
rule-files:
  - custom.rules

af-packet:
  - interface: eth0
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes
    # Aggiungiamo questi parametri per risolvere il problema
    buffer-size: 32768
    block-size: 32768
    ring-size: 2048

outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: /var/log/suricata/eve.json
      types:
        - alert

  - fast:
      enabled: yes
      filename: /var/log/suricata/fast.log
      append: yes

logging:
  default-log-level: info
