version: '3.8'

services:
  # Web Server - Nginx
  web-server:
    build: ./web-server
    ports:
      - '80:80'
    networks:
      - frontend
      - monitoring
    depends_on:
      - database
    container_name: web-server

  # Database - PostgreSQL
  database:
    build: ./database
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - '5432:5432'
    networks:
      - backend
      - monitoring
    container_name: database

  # Client machine for testing
  client:
    build: ./client
    networks:
      - frontend
      - backend
    depends_on:
      - web-server
      - database
    container_name: client

  # Suricata IDS
  suricata:
    build: ./suricata
    networks:
      - frontend
      - backend
      - monitoring
    volumes:
      - ./suricata/logs:/var/log/suricata
    container_name: suricata
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    command:
      [
        '/usr/bin/suricata',
        '-c',
        '/etc/suricata/suricata.yaml',
        '--af-packet',
        '-v',
      ]

  # Elasticsearch
  elasticsearch:
    build: ./elk-stack/elasticsearch
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - '9200:9200'
    networks:
      - elk
    container_name: elasticsearch

  # Logstash
  logstash:
    build: ./elk-stack/logstash
    volumes:
      - ./suricata/logs:/suricata-logs
    depends_on:
      - elasticsearch
    networks:
      - elk
    container_name: logstash

  # Kibana
  kibana:
    build: ./elk-stack/kibana
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - elk
    container_name: kibana

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  monitoring:
    driver: bridge
  elk:
    driver: bridge
