version: '3'

services:
  web:
    container_name: web
    build: ./web
    networks:
      security_network:
        ipv4_address: 172.18.0.2

  db:
    container_name: db
    build: ./database
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    networks:
      security_network:
        ipv4_address: 172.18.0.3

  suricata:
    container_name: suricata
    build: ./suricata
    volumes:
      - ./suricata/rules:/etc/suricata/rules:ro
      - ./logs:/var/log/suricata:rw
    network_mode: 'container:web'
    depends_on:
      - web
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

  client:
    container_name: client
    build: ./client
    volumes:
      - ./scripts:/scripts
    networks:
      security_network:
        ipv4_address: 172.18.0.4
    depends_on:
      - web
      - db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
    networks:
      security_network:
        ipv4_address: 172.18.0.5
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9200']
      interval: 10s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      security_network:
        ipv4_address: 172.18.0.6

  filebeat:
    build: ./filebeat
    container_name: filebeat
    volumes:
      - ./logs:/var/log/suricata:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      security_network:
        ipv4_address: 172.18.0.7
    restart: unless-stopped

networks:
  security_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
