version: '3'

services:
  web:
    container_name: web
    build: ./web
    networks:
      security_network:
        ipv4_address: 172.18.0.2

  db:
    container_name: db
    build: ./database
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    networks:
      security_network:
        ipv4_address: 172.18.0.3

  suricata:
    container_name: suricata
    build: ./suricata
    volumes:
      - ./suricata/rules:/etc/suricata/rules:ro
      - ./logs:/var/log/suricata:rw
    network_mode: 'container:web'
    depends_on:
      - web
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

  client:
    container_name: client
    build: ./client
    volumes:
      - ./scripts:/scripts
    networks:
      security_network:
        ipv4_address: 172.18.0.4
    depends_on:
      - web
      - db

networks:
  security_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
