version: '3.8'

services:
  # Web Server (Nginx)
  web:
    build: ./web-server
    ports:
      - '8080:80'
    networks:
      - security_network

  # Database (PostgreSQL)
  db:
    build: ./database
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - '5432:5432'
    networks:
      - security_network

  # Client machine
  client:
    build: ./client
    networks:
      - security_network
    depends_on:
      - web
      - db

  # Suricata IDS
  suricata:
    build: ./suricata
    network_mode: 'host'
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
      - IPC_LOCK
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./suricata/logs:/var/log/suricata
      - ./suricata/config:/etc/suricata
    ulimits:
      memlock: -1
    # Privileged mode per accesso completo alla rete
    privileged: true
    environment:
      - SURICATA_OPTIONS=--af-packet

  # ELK Stack
  elasticsearch:
    build: ./elk/elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
    networks:
      - security_network
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    build: ./elk/logstash
    ports:
      - '5044:5044'
    networks:
      - security_network
    depends_on:
      - elasticsearch

  kibana:
    build: ./elk/kibana
    ports:
      - '5601:5601'
    networks:
      - security_network
    depends_on:
      - elasticsearch

networks:
  security_network:
    driver: bridge

volumes:
  es_data:
